### ISSUE TITLE
(No) Use of Variables in CronJob Homey App

### ISSUE THREAD

**Issue by JirikiAiki** [stefan-schweiger/dev.schweiger.cron-job#1]
I just had first test and I am still enthusiastic.
I just saw that when entering a schedule there is a sticker that allows you to use variables in the parameters.
![Cronjob test variables](https://github.com/stefan-schweiger/dev.schweiger.cron-job/assets/148859797/47b32c4f-c982-412a-9eaf-acb067c51720)
As I know a bit about LINUX/UNIX crontab, I doubted that those work, but I do not really know about the implementation (not at all used to the *Script language). 
So I ran a test and the result is: **Never use variables in setting up cronjobs**. Write the parameters in **pure text**!

To me it is OK that you cannot use variables here - just a hint to Stefan: There are cards to which *you can enter a text, but you are not able to link variables to the parameter*. I do not know how to realise this, but I would recommend it to avoid misconception and multiple users who ask why their cronjobs are not fired or deinstall this wonderful app right after first frustration.

And good luck with this app

**Comment by stefan-schweiger** [comment]
Thanks for the input, I will have a look if I can either get variables to work or disable their input.

**Comment by stefan-schweiger** [comment]
Seems like it's not possible to get this to work sadly due to limitations in the Homey SDK :( I have added a hint that you are not able to use tokens/variables to the latest version.
